2018.8.6

diff --git a/common/adk b/common/adk
--- a/common/adk
+++ b/common/adk
@@ -4,6 +4,8 @@
 # License: GPL v3+
 
 
+set -u
+
 is_mounted() { mountpoint -q "$1"; }
 
 mount_image() {
@@ -29,11 +31,10 @@ mount_image() {
     done
   fi
   if ! is_mounted $mountPoint; then
-    echo -e "\n(!) $IMG mount failed... abort\n"
+    echo -e "\n(!) Failed to mount $IMG\n"
     exit 1
   fi
 }
-
 
 mountPoint=/magisk
 
@@ -42,17 +43,15 @@ mount /data 2>/dev/null
 [ -d /data/adb/magisk ] && IMG=/data/adb/magisk.img || IMG=/data/magisk.img
 
 if [ ! -d /data/adb/magisk ] && [ ! -d /data/magisk ]; then
-	echo -e "\n(!) No Magisk installation found or installed version is not supported\n"
-	exit 1
+  echo -e "\n(!) No Magisk installation found or installed version is not supported\n"
+  exit 1
 fi
 
 mount_image $IMG $mountPoint
 
-
 resdata=true
 . /tmp/core.sh
 resdata
-
 
 umount $mountPoint
 losetup -d $loopDevice
